language: node_js
sudo: required

services:
  - docker

node_js:
  - "4.4.2"

before_install:

install:
  - npm install

script:
  # 2.8.11 arangodb
  - docker pull arangodb/arangodb:2.8.11
  - docker run --name arangodb2.8.11 -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb/arangodb:2.8.11
  - npm test
  - docker stop arangodb2.8.11
  # latest arangodb
  - docker pull arangodb/arangodb
  - docker run --name arangodb -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb/arangodb
  - npm test
  - docker stop arangodb
