language: node_js
sudo: required

services:
  - docker

node_js:
  - "4.4.2"

before_install:
- docker pull arangodb/arangodb
- docker run -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb/arangodb

install:
  - npm install

script:
  - npm test
